global:
  scrape_interval: 5s  # ⏱ Frecuencia de recolección de métricas

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']  # 👈 Nombre del contenedor backend
